// SPDX-License-Identifier: Apache-2.0
export type ReceiptTaskStatus = 'pending' | 'processing' | 'review' | 'complete' | 'failed';

export interface ExtractedItem {
  /** Stable id generated by the edge function. Optional for backward compat with rows saved before this feature. */
  id?: string;
  /** Localized name (target language). */
  name: string;
  /** Original name verbatim from the receipt. Optional for backward compat. */
  nameOriginal?: string;
  price: number;
  qty: number;
}

export interface ParticipantCount {
  participantId: string;
  count: number;
}

/** New mapped_items shape — keyed by stable item id, with per-participant counts. */
export interface MappedItem {
  itemId: string;
  participantCounts: ParticipantCount[];
}

/** Old shape kept as a separate type so the load adapter can recognize it. */
export interface LegacyMappedItem {
  item_index: number;
  participant_ids: string[];
}

export interface ReceiptTask {
  id: string;
  trip_id: string;
  created_by: string;
  status: ReceiptTaskStatus;
  receipt_image_path: string | null;
  extracted_merchant: string | null;
  extracted_items: ExtractedItem[] | null;
  extracted_total: number | null;
  extracted_currency: string | null;
  extracted_date: string | null;
  extracted_category: string | null;
  confirmed_total: number | null;
  tip_amount: number;
  /** Either new shape or legacy shape — load adapter normalizes on read. */
  mapped_items: (MappedItem | LegacyMappedItem)[] | null;
  expense_id: string | null;
  error_message: string | null;
  created_at: string;
  updated_at: string;
}

export interface CreateReceiptTaskInput {
  trip_id: string;
  receipt_image_path?: string;
}
