-- Add trip_code column for shareable URLs
-- Migration 006: Add trip_code support for URL-based access control

-- Add trip_code column (nullable initially, we'll populate then make NOT NULL)
ALTER TABLE trips ADD COLUMN trip_code TEXT;

-- Create unique index for fast lookups
CREATE UNIQUE INDEX idx_trips_trip_code ON trips(trip_code);

-- Note: trip_code values will be generated by application code
-- After all existing trips have codes, run: ALTER TABLE trips ALTER COLUMN trip_code SET NOT NULL;
